### Quiz -1

In [43]:
import numpy as np
import pandas as pd

In [6]:
a = np.array([1, 2, 3 , 4])

In [4]:
type(a)

numpy.ndarray

In [13]:
a.dtype

dtype('int32')

In [9]:
a.reshape((2, -1))

array([[1, 2],
       [3, 4]])

In [10]:
a.reshape((4, -1))

array([[1],
       [2],
       [3],
       [4]])

In [11]:
list(a)

[1, 2, 3, 4]

In [12]:
a.tolist()

[1, 2, 3, 4]

In [14]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Assignment -1 

In [19]:
a =np.zeros(shape=10, dtype= int)

In [20]:
a[5] = 1

In [21]:
a

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [22]:
# arange([start,] stop[, step,], dtype=None, *, like=None)
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [26]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
a = np.array([1,2,0,0,4,0])

In [31]:
a != 0

array([ True,  True, False, False,  True, False])

In [32]:
np.where(a != 0)

(array([0, 1, 4], dtype=int64),)

In [33]:
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [35]:
np.random.rand(10,10).min() , np.random.rand(10,10).max()

(0.0007053712681810431, 0.9647652690915336)

In [38]:
np.random.randint(low = 10, high=100, size=(10, 10)).min(), np.random.randint(low = 10, high=100, size=(10, 10)).max()

(10, 98)

In [40]:
np.random.randint(low=10, high=100, size=(30,))

array([23, 67, 62, 65, 41, 91, 89, 21, 89, 45, 50, 74, 54, 27, 52, 57, 81,
       99, 81, 63, 16, 46, 91, 38, 91, 70, 75, 75, 91, 78])

In [42]:
np.arange(0, 30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### Quiz 2

In [44]:
ary = np.array([1,2,3,5,8])

In [45]:
ary + 1

array([2, 3, 4, 6, 9])

In [46]:
ary * 2

array([ 2,  4,  6, 10, 16])

In [47]:
a = np.array([[1,2,3],[0,1,4]])

b = np.zeros((2,3), dtype=np.int16)

c = np.ones((2,3), dtype=np.int16)

In [51]:
a

array([[1, 2, 3],
       [0, 1, 4]])

In [52]:
c

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [55]:
d = a + b + c

In [56]:
d[1,2] 

5

In [58]:
# (shape: _ShapeLike, fill_value: Any
np.full(shape=(2, 3), fill_value=99)

array([[99, 99, 99],
       [99, 99, 99]])

In [60]:
a = [1, 2, 3]
print(type(np.array(a)))

<class 'numpy.ndarray'>


In [61]:
name = 'alok'
name[0] * 5

'aaaaa'

In [63]:
name * 5

'alokalokalokalokalok'

In [62]:
l = ["a", "b", "c", "d", "e"]

In [65]:
l + l

['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e']

In [66]:
l * 2

['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e']

In [69]:
np.array(l) * 5

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int32')) -> None

In [1]:
import pandas

In [3]:
pandas.read_csv('../data/iris.csv').head()

sepal_length_(cm)  sepal_width_(cm)  petal_length_(cm)  petal_width_(cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [4]:
import pandas as p

In [5]:
p.read_csv('../data/iris.csv').head()

sepal_length_(cm)  sepal_width_(cm)  petal_length_(cm)  petal_width_(cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [6]:
from pandas import *

In [8]:
df_iris = read_csv('../data/iris.csv')

In [11]:
df_iris.isnull().any()

sepal_length_(cm)    False
sepal_width_(cm)     False
petal_length_(cm)    False
petal_width_(cm)     False
species              False
dtype: bool

In [12]:
df_titanic = read_csv('../data/titanic.csv')

In [19]:
# fill missing value with zero
df_titanic['Age'].fillna(0)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     0.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [20]:
# fill missing value with mean
df_titanic['Age'].fillna(df_titanic['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [21]:
df_titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
df_titanic.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [28]:
# import numpy as np
# np.array(df_titanic.Embarked, fill_value = 0)

In [32]:
df_titanic.dropna().shape

(183, 12)

In [33]:
df_titanic.shape

(891, 12)

In [ ]:
df_titanic.drop(columns = [''])